name: Tailscale SSH Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: SSH Test
        uses: cross-the-world/ssh-pipeline@master
        with:
          host: ${{ secrets.ATLAS_HOST }}
          user: ${{ secrets.ATLAS_USER }}
          key: ${{ secrets.ATLAS_SSH_KEY }}
          cmds: echo "hi from atlas-2"